#include "hash_tables.h"

/**
 * key_index - gives the index of the key
 * generates index by taking the modulo of the hash value
 * generated by the hash_djb2 function by the size
 * of the hash table array
 *
 * @key: the string to be used to generate the index
 * @size: size of the array of the hash table
 *
 * Return: index at which to insert the data
 */
unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int index;

	index = (hash_djb2(key)) % size;
	return (index);
}
